version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  semantic-worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: semantic_worker_api
    ports:
      - "8081:8081"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=files_chunks
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - CHUNK_SIZE=800
      - CHUNK_OVERLAP=120
      - MAX_TOP_K=8
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./worker:/app
      - /tmp:/tmp  # For temporary file processing
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local